### ISSUE TITLE
Why update the value of mu?

### ISSUE THREAD

**Issue by AnhaoROMA** [xueshengke/Tensor-TNNR#1]
Hi, Mr Xue.

Sorry to bother you but I want to learn why you update the value of mu (In the line 67, in File tnn_admm.m of Dir "algorithms")? I don't think you have ever mentioned it in you paper.

I think it is too hard for you to remember since this paper was published 4 years ago. But it couldn't be better if you can offer me some help.

Best regards.

**Comment by xueshengke** [comment]
This ‘mu’ can be considered as a constraint. The larger the value is, the better the completion effect will be.
From the principle in the matrix completion, the ‘mu’ should start from a very small value, then it gradually increases to a huge value, to reduce the error and enhance the matrix completion.

**Comment by AnhaoROMA** [comment]
I see. As you said, the Completion task requires the result-tensor to be as close as the obtained-tensor.

Thank you very much for your help!

Best regards.
